import { useEffect, useState } from 'react';
import useSWR from "swr";
import Head from 'next/head';
import NavBar from '../components/molecules/NavBar';
import Footer from '../components/atoms/Footer';
import '../styles/globals.css';

const fetcher = (url) => fetch(url).then((res) => res.json());

function MyApp({ Component, pageProps }) {
  const [userProps, setUserProps] = useState({ logged: false });
  const [oauthServices, setOauthServices] = useState([]);
  const swrUser = useSWR('api/user', fetcher);
  const swrOauthServices = useSWR('api/oauth-providers', fetcher);

  useEffect(() => {
    if (swrUser.data) {
      setUserProps(() => ({ ...swrUser.data.props }));
    };
    if (swrUser.error) console.log(swrUser.error);
  }, [swrUser]);

  useEffect(() => {
    if (swrOauthServices.data) {
      if (swrOauthServices.data.length > 0) setOauthServices(() => (swrOauthServices.data))
    }
    if (swrOauthServices.error) console.log(swrOauthServices.error)
  }, [swrOauthServices]);

  return (
    <>
      <Head>
        <title>Oauth in Next.js with passport and nextConnect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar userProps={userProps} enabled={oauthServices.length > 0} />
      <Component {...pageProps} userProps={userProps} oauthServices={oauthServices} />
      <Footer />
    </>);
};

export default MyApp;
